stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay2

test_job:
  stage: test
  image: node:14
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Running tests..."
    - npm test

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - docker build -t $DOCKER_HUB_USERNAME/myapp:latest .
    - docker push $DOCKER_HUB_USERNAME/myapp:latest
    - docker tag $DOCKER_HUB_USERNAME/myapp:latest $DOCKER_HUB_USERNAME/myapp:v1.0.0
    - docker push $DOCKER_HUB_USERNAME/myapp:v1.0.0