services:
 
  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=neo4j+s://fddf35fa.databases.neo4j.io
      - DATABASE_USER=neo4j
      - DATABASE_PASSWORD=HfZENvbpnjg6Qas_DO36OD4r20nO0u7bso2EY797X2Q

    restart: always

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://54.167.41.40:3000
    restart: always

